### ISSUE TITLE
data/ucf/frames.json missing?

### ISSUE THREAD

**Issue by ptmorris03** [srikarym/CCTV-Gun#1]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmdetection/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmdetection).

### 🐞 Describe the bug

Many thanks for releasing the annotations in CCTV-Gun, this is very realistic data with high-quality labels. Unfortunately, I am having trouble with the instructions for the UCF dataset:

following the instructions for downloading the UCF dataset and running python3 scripts/copy_images_ucf.py produces the error

```FileNotFoundError: [Errno 2] No such file or directory: 'data/ucf/frames.json'```

frames.json appears to be missing from the repository. What is the correct way to obtain it?

### Environment

```Package             Version
------------------- --------
contourpy           1.0.7
cycler              0.11.0
fonttools           4.39.2
importlib-resources 5.12.0
kiwisolver          1.4.4
matplotlib          3.7.1
numpy               1.24.2
opencv-python       4.7.0.72
packaging           23.0
Pillow              9.4.0
pip                 22.0.4
pyparsing           3.0.9
python-dateutil     2.8.2
setuptools          58.1.0
six                 1.16.0
zipp                3.15.0
```

**Comment by srikarym** [comment]
Hi Paul, the [file](https://github.com/srikarym/CCTV-Gun/blob/master/data/ucf/frames.json) should be available now

**Comment by ptmorris03** [comment]
Thanks! It's working now.
