### ISSUE TITLE
Conda install not working

### ISSUE THREAD

**Issue by BroderickHigby** [srikarym/CCTV-Gun#2]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmdetection/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmdetection).

### 🐞 Describe the bug

When installing via conda, I get the error that none of the packages can be found for the packages in requirements/requirements_cctv_gun.txt 

Anaconda says I need to add further channels. Pip install in a virtualenv doesn't work either. I've tried this on a local iMac as well as an AWS GPU instance. This occurs on the first command: 
conda create --name myenv --file requirements/requirements_cctv_gun.txt

When I search for the channels on anaconda.org, they show up as under the conda-forge channel which is a channel that's already added.

### Environment

I've installed PyTorch 1.13.1 as well as mmcls=0.25.0, mmcv-full=1.7.0 and torch=1.13.0.

The collect_env.py 

### Additional information

What version of anaconda did you use? I ran everything else according to the requirements file.

**Comment by srikarym** [comment]
@BroderickHigby  I updated the steps in [Readme](https://github.com/srikarym/CCTV-Gun#requirements), could you check now?

**Comment by BroderickHigby** [comment]
Sorry I was at CVPR. It still says packages not found when running the first step. It may be my python3 version. I have 3.10.9

Here is my output from running the `env.yml` file:

```
conda env create  -f requirements/env.yml 
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - xz==5.2.6=h5eee18b_0
  - mkl==2021.4.0=h06a4308_640
  - sqlite==3.39.3=h5082296_0
  - mkl_fft==1.3.1=py39hd3c417c_0
  - ld_impl_linux-64==2.38=h1181459_1
  - _openmp_mutex==5.1=1_gnu
  - libgomp==11.2.0=h1234567_1
  - certifi==2022.9.24=py39h06a4308_0
  - cudatoolkit==11.3.1=h2bc3f7f_2
  - readline==8.2=h5eee18b_0
  - ncurses==6.3=h5eee18b_3
  - mkl_random==1.2.2=py39h51133e4_0
  - tk==8.6.12=h1ccaba5_0
  - openssl==1.1.1q=h7f8727e_0
  - libgcc-ng==11.2.0=h1234567_1
  - numpy-base==1.23.3=py39h31eccc5_1
  - python==3.9.13=haa1d7c7_2
  - libstdcxx-ng==11.2.0=h1234567_1
  - ca-certificates==2022.10.11=h06a4308_0
  - intel-openmp==2021.4.0=h06a4308_3561
  - zlib==1.2.13=h5eee18b_0
  - libffi==3.3=he6710b0_2
  - mkl-service==2.4.0=py39h7f8727e_0
 ```

**Comment by srikarym** [comment]
When I run the same command, Solving environment step doesn't fail, I use `conda 4.12.0` (installed via miniconda) and `Python 3.9.12`

```
conda env create -f requirements/env.yml 
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
Collecting package metadata (repodata.json): done
Solving environment: done
```
I've again updated the installation steps in [Readme](https://github.com/srikarym/CCTV-Gun#requirements). Could you check now?
