### ISSUE TITLE
How to use the model to predict for a picture

### ISSUE THREAD

**Issue by willswordh** [srikarym/CCTV-Gun#3]
how to run the model for testing on a single picture? Thanks!

**Comment by srikarym** [comment]
Our repo uses mmdetection as the underlying library. Please see [this](https://mmdetection.readthedocs.io/en/latest/user_guides/index.html#train-test).

**Comment by willswordh** [comment]
@srikarym Thanks for your quick response! I checked the "Dataset and evaluator config" in the "Learn about Config" section, is that part of code that I need to run to test on a single picture? There is no command line option for testing on a single picture or video? Thanks a lot!

**Comment by srikarym** [comment]
@willswordh I think so; we've not evaluated it on individual images, so I'm not sure. I'm sorry I couldn't help you more.

**Comment by willswordh** [comment]
@srikarym Thanks a lot nonetheless! I am wondering how did you get the result in Figure 4: Qualitative results of the best-performing models. They seemed to be predicted using your model on the single image level. 

Could you tell me if I want to test on a single image, is it correct that the "dataset-config" need to be changed to put in the file of a image while "config <path/to/model/config.py>" maintains unchanged using your approach to test one entire dataset? Thanks

**Comment by srikarym** [comment]
I assume that would work - use an existing config but point to a folder (by updating the dataset-config) that contains your target images.
